services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - '8009:80'
#    environment:
#      PMA_ARBITRARY: 1
#      PMA_USER: "root"
#      PMA_PASSWORD_FILE: /run/secrets/db_password
#      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - '8008:80'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

volumes:
  db_data: null

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
